---
- name: Deploy hosts.j2
  hosts: all
  tasks:
    - name: Using template module
      ansible.builtin.template:
        src: templates/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
